import * as fs from "node:fs/promises";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { artifactPathPattern, artifactStore, atomicWrite, driftConfig, exists, git, hash, mergeInProgress, now, python, Records, run, safePath, trackArtifacts, updateConfig, withLock } from "./state.ts";
import type { Pending, Receipt, RecordData } from "./state.ts";
export { trackArtifacts } from "./state.ts";
import { hasAttribute, indexAttributeLine, indexDriver } from "./git-drivers.ts";
import { changelogState, sections } from "./changelog.ts";

export interface ArtifactInput {
  feature: string;
  kind: "research" | "plan" | "handoff";
  slug: string;
  body: string;
  status?: string;
  source_research?: string;
  previous_handoff?: string;
  related_artifacts?: string[];
  next_session_profile?: string;
  /** One changelog bullet, written as a changelog.d/ fragment beside the artifact when the repo has opted in. */
  changelog?: { section: string; text: string };
}

const fragmentPathPattern = /^changelog\.d\/[A-Za-z0-9][A-Za-z0-9_-]{0,159}\.md$/;

const profilePattern = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

// The states a new artifact may be published in; the first is the default. Later
// transitions (in-progress, superseded) are in-place frontmatter edits, not publications.
const statuses: Record<ArtifactInput["kind"], string[]> = {
  research: ["complete"],
  plan: ["pending"],
  handoff: ["in-progress", "complete"],
};

const headings = {
  research: ["Research Question", "Summary", "Detailed Findings", "Code References", "Open Questions"],
  plan: ["Objective", "Source Research", "Starting Point", "Key Files", "Implementation Sequence", "Decisions & Constraints", "Open Questions"],
  handoff: ["Objective", "Source Documents", "Status", "What Changed", "Codebase Context", "What Deviated from Plan", "Open Questions", "Next Steps"],
};
const builder = fileURLToPath(new URL("../scripts/build-index.py", import.meta.url));

function optionalReference(value: unknown, field: string): string | undefined {
  if (value === undefined) return undefined;
  if (typeof value !== "string") throw new Error(`${field} must be an artifact path string or omitted`);
  return value.trim() || undefined;
}

async function validate(repo: string, input: ArtifactInput, changelogEnabled: boolean): Promise<ArtifactInput> {
  if (!/^[A-Za-z0-9][A-Za-z0-9_-]{0,79}$/.test(input.feature)) throw new Error("Feature must be a safe folder identifier (letters, digits, hyphens, underscores)");
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(input.slug) || input.slug.length > 80) throw new Error("Slug must be lowercase words separated by hyphens");
  if (!Object.hasOwn(headings, input.kind)) throw new Error("Unknown artifact kind");
  if (typeof input.body !== "string" || Buffer.byteLength(input.body) > 256 * 1024 || /^---(?:\r?\n|$)/.test(input.body.trimStart())) {
    throw new Error("Provide Markdown body only (no frontmatter), at most 256 KiB");
  }
  const missing = headings[input.kind].filter((heading) => !new RegExp(`^## ${heading}\\s*$`, "m").test(input.body));
  if (missing.length) throw new Error(`Missing sections: ${missing.join(", ")}`);
  if (input.status !== undefined && !statuses[input.kind].includes(input.status)) {
    throw new Error(`A new ${input.kind} must have status ${statuses[input.kind].join(" or ")}`);
  }
  if (input.next_session_profile !== undefined && typeof input.next_session_profile !== "string") {
    throw new Error("next_session_profile must be a lowercase hyphenated profile name or omitted");
  }
  const nextProfile = input.next_session_profile?.trim() || undefined;
  if (nextProfile !== undefined && !profilePattern.test(nextProfile)) {
    throw new Error("next_session_profile must be a lowercase hyphenated profile name");
  }
  if (input.kind !== "handoff" && nextProfile !== undefined) {
    throw new Error("next_session_profile is only supported for handoff artifacts");
  }
  let changelog: ArtifactInput["changelog"];
  if (input.changelog !== undefined) {
    if (!changelogEnabled) throw new Error("This repository's changelog is not generated by Drift (it has no origin remote or no CHANGELOG.md, or .drift.json turns it off): omit changelog, or run /drift-changelog on to force it");
    const { section, text } = (input.changelog ?? {}) as { section?: unknown; text?: unknown };
    if (typeof section !== "string" || !(sections as readonly string[]).includes(section)) throw new Error(`changelog.section must be one of ${sections.join(", ")}`);
    if (typeof text !== "string" || !text.trim() || Buffer.byteLength(text) > 4096 || /\n\s*\n/.test(text.trim()) || /<!--|-->/.test(text)) {
      throw new Error("changelog.text must be one non-empty bullet of at most 4 KiB, without blank lines or HTML comments");
    }
    changelog = { section, text: text.trim() };
  }
  const source = optionalReference(input.source_research, "source_research");
  const previous = optionalReference(input.previous_handoff, "previous_handoff");
  if (input.related_artifacts !== undefined && !Array.isArray(input.related_artifacts)) throw new Error("related_artifacts must be an array of artifact paths or omitted");
  const related = input.related_artifacts?.map((ref, index) => optionalReference(ref, `related_artifacts[${index}]`)).filter((ref): ref is string => ref !== undefined);
  const refs = [source, previous, ...(related ?? [])].filter((ref): ref is string => ref !== undefined);
  for (const ref of refs) {
    if (!/^drift\/.+\.md$/.test(ref) || ref.includes("\\") || ref.split("/").some((part) => part === ".." || part === ".")) throw new Error(`Invalid artifact reference: ${JSON.stringify(ref)}`);
    const path = await safePath(repo, resolve(repo, ref));
    if (!(await fs.stat(path)).isFile()) throw new Error(`Artifact reference is not a file: ${ref}`);
  }
  // Stable ordering/normalization makes retries idempotent within the owned interval.
  return {
    feature: input.feature, kind: input.kind, slug: input.slug, body: input.body.trim() + "\n",
    ...(input.status !== undefined ? { status: input.status } : {}),
    ...(source ? { source_research: source } : {}),
    ...(previous ? { previous_handoff: previous } : {}),
    ...(related ? { related_artifacts: [...new Set(related)] } : {}),
    ...(nextProfile ? { next_session_profile: nextProfile } : {}),
    ...(changelog ? { changelog } : {}),
  };
}

/** `root` is the checkout whose drift/ is in use (see artifactStore), so the ignore rule lands beside the folder. */
async function ensureArtifactPolicy(repo: string, paths: string[], tracked: boolean): Promise<void> {
  if (!tracked) {
    const path = await safePath(repo, join(repo, ".gitignore"));
    const text = await exists(path) ? await fs.readFile(path, "utf8") : "";
    if (!text.split(/\r?\n/).includes("/drift/")) {
      const mode = await exists(path) ? (await fs.stat(path)).mode & 0o777 : 0o644;
      await atomicWrite(path, text + (text && !text.endsWith("\n") ? "\n" : "") + "/drift/\n", mode);
    }
  }
  for (const path of paths) await checkArtifactPolicy(repo, path, tracked);
}

async function checkArtifactPolicy(repo: string, path: string, tracked: boolean): Promise<void> {
  // Exit 1 means not ignored; all other Git failures still stop the write.
  const ignored = Boolean((await git(repo, ["check-ignore", "--no-index", path], 1)).trim());
  if (tracked && ignored) throw new Error(`trackArtifacts is true in .drift.json, but Git ignores ${path}. Resolve the ignore rule explicitly; Drift will not change it or force-add files.`);
  if (!tracked && !ignored) throw new Error(`Drift artifacts must be ignored by default, but Git does not ignore ${path}. To commit artifacts, explicitly set {"trackArtifacts":true} in the repository-root .drift.json; otherwise resolve the ignore exception.`);
}

// The ignore rules that mean "the root drift/ folder": the publisher's own line and its hand-written variants.
const driftIgnoreRules = new Set(["/drift/", "/drift", "drift/", "drift"]);
// The index and a real artifact-shaped path: both must land on the chosen side of the policy.
const policyProbes = ["drift/INDEX.md", "drift/feature/001-handoff-check.md"];

export type TrackingRequest = "on" | "off" | "toggle" | "status";

/** The rule deciding a path, as `"pattern" in source`; verbose output is "source:line:pattern<TAB>path". */
async function decidingRule(repo: string, path: string): Promise<string | undefined> {
  const line = (await git(repo, ["check-ignore", "--no-index", "--verbose", "--non-matching", path], 1)).trim();
  const match = /^(.*):\d+:(.+)\t/.exec(line);
  return match ? `rule "${match[2]}" in ${match[1]}` : undefined;
}

/** The first probe on the wrong side of the policy, explained; undefined when Git agrees with it. */
async function policyProblem(repo: string, tracked: boolean): Promise<string | undefined> {
  for (const path of policyProbes) {
    const ignored = Boolean((await git(repo, ["check-ignore", "--no-index", path], 1)).trim());
    if (ignored !== tracked) continue;
    const rule = await decidingRule(repo, path);
    // Git names no rule for a file under a re-included directory, so describe the usual cause instead.
    return tracked ? `Git still ignores ${path} because of ${rule ?? "an ignore rule"}` : `Git does not ignore ${path}${rule ? ` because of ${rule}` : "; an exception such as !/drift/ re-includes it"}`;
  }
  return undefined;
}

/**
 * The user's explicit tracking choice, as a command: turn committed artifacts on or off, flip them, or report.
 * Edits only `.drift.json` and Drift's own `drift/` ignore rule, then proves the result with Git; if another rule
 * defeats the choice, both files are restored and that rule is named. Never stages, commits or untracks.
 */
export async function setArtifactTracking(repo: string, request: TrackingRequest): Promise<string> {
  const current = await trackArtifacts(repo); // Validates any existing config before touching it.
  if (request === "status") {
    const problem = await policyProblem(repo, current);
    const state = current ? "tracked: trackArtifacts is true in .drift.json" : "ignored (the default)";
    return `Drift artifacts in this repo are ${state}.${problem ? `\nBut ${problem}; run /drift-track-artifacts ${current ? "on" : "off"} to repair it.` : ""}`;
  }
  const tracked = request === "toggle" ? !current : request === "on";
  const config = await safePath(repo, join(repo, ".drift.json"));
  const ignore = await safePath(repo, join(repo, ".gitignore"));
  const attributes = await safePath(repo, join(repo, ".gitattributes"));
  const originalConfig = await exists(config) ? await fs.readFile(config, "utf8") : undefined;
  const originalIgnore = await exists(ignore) ? await fs.readFile(ignore, "utf8") : undefined;
  const originalAttributes = await exists(attributes) ? await fs.readFile(attributes, "utf8") : undefined;
  const modeOf = async (path: string) => await exists(path) ? (await fs.stat(path)).mode & 0o777 : 0o644;
  const changes: string[] = [];
  let nextIgnore = originalIgnore;
  let nextAttributes = originalAttributes;
  if (tracked) {
    const lines = originalIgnore?.split(/(?<=\n)/) ?? [];
    const kept = lines.filter((line) => !driftIgnoreRules.has(line.trim()));
    if (kept.length !== lines.length) {
      nextIgnore = kept.join("");
      changes.push(`removed ${lines.length - kept.length} drift/ rule(s) from .gitignore`);
    }
  } else if (!(originalIgnore ?? "").split(/\r?\n/).some((line) => driftIgnoreRules.has(line.trim()))) {
    const text = originalIgnore ?? "";
    nextIgnore = text + (text && !text.endsWith("\n") ? "\n" : "") + "/drift/\n";
    changes.push("added /drift/ to .gitignore");
  }
  // A committed index meets other threads' copies at rebase; the attribute names the driver that merges them.
  // Committed with the repo and inert until a clone installs the command, so it stays in place on "off".
  if (tracked && !hasAttribute(originalAttributes ?? "", indexDriver.path, indexDriver.name)) {
    const text = originalAttributes ?? "";
    nextAttributes = text + (text && !text.endsWith("\n") ? "\n" : "") + indexAttributeLine + "\n";
    changes.push(`added "${indexAttributeLine}" to .gitattributes`);
  }
  // Off writes false only over an explicit true: a missing file already means the default.
  const writeConfig = tracked !== current && (tracked || originalConfig !== undefined);
  if (writeConfig) {
    await updateConfig(repo, { trackArtifacts: tracked }); // Keeps the repo's other Drift settings.
    changes.unshift(`set trackArtifacts to ${tracked} in .drift.json`);
  }
  if (nextIgnore !== originalIgnore) await atomicWrite(ignore, nextIgnore!, await modeOf(ignore));
  if (nextAttributes !== originalAttributes) await atomicWrite(attributes, nextAttributes!, await modeOf(attributes));
  const problem = await policyProblem(repo, tracked);
  if (problem) {
    const restore = async (path: string, original: string | undefined, changed: boolean) => {
      if (!changed) return;
      if (original === undefined) await fs.rm(path, { force: true });
      else await atomicWrite(path, original, await modeOf(path));
    };
    await restore(config, originalConfig, writeConfig);
    await restore(ignore, originalIgnore, nextIgnore !== originalIgnore);
    await restore(attributes, originalAttributes, nextAttributes !== originalAttributes);
    throw new Error(`${problem}. Nothing was changed; resolve that rule, then run /drift-track-artifacts ${tracked ? "on" : "off"} again.`);
  }
  const summary = changes.length ? `: ${changes.join("; ")}` : "; nothing needed changing";
  if (tracked) {
    return [
      `Drift artifacts are now tracked${summary}.`,
      "Nothing was staged or committed. Review drift/ for anything that should not be shared, then commit:",
      "  git add .drift.json .gitignore .gitattributes drift && git commit -m \"chore: track Drift artifacts\"",
      "In clones where Drift runs, drift/INDEX.md now merges itself on rebase; the merge driver is installed at session start.",
    ].join("\n");
  }
  const committed = (await git(repo, ["ls-files", "--", "drift"])).split("\n").filter(Boolean).length;
  return [
    `Drift artifacts are now ignored${summary}.`,
    ...(committed ? [
      `${committed} file(s) under drift/ are already committed; ignoring does not untrack them. To stop tracking them and keep the files:`,
      "  git rm -r --cached drift && git commit -m \"chore: stop tracking Drift artifacts\"",
    ] : []),
  ].join("\n");
}

/**
 * A tracked index is committed, so two worktrees' copies meet at rebase once there is somewhere to rebase from.
 * With an origin remote the attribute is written here, the same way the ignore line is; returns whether it was.
 */
export async function ensureIndexAttribute(repo: string): Promise<boolean> {
  const attributes = await safePath(repo, join(repo, ".gitattributes"));
  const existing = await exists(attributes) ? await fs.readFile(attributes, "utf8") : "";
  if (hasAttribute(existing, indexDriver.path, indexDriver.name)) return false;
  const mode = await exists(attributes) ? (await fs.stat(attributes)).mode & 0o777 : 0o644;
  await atomicWrite(attributes, existing + (existing && !existing.endsWith("\n") ? "\n" : "") + indexAttributeLine + "\n", mode);
  return true;
}

/**
 * Session-start refresh. Artifacts written by hand or by another host may never have reached the index, so
 * render it from frontmatter and write it when missing or different. Never creates drift/ or an empty index,
 * and never edits .gitignore: a policy mismatch is reported, not repaired. Returns whether it wrote.
 */
export async function syncIndex(repo: string, interpreter?: string): Promise<boolean> {
  const tracked = await trackArtifacts(repo);
  const { root } = await artifactStore(repo, tracked);
  const drift = await safePath(root, join(root, "drift"));
  if (!(await exists(drift))) return false;
  // Mid-rebase the file may hold conflict markers the driver is about to resolve; writing now would race it.
  if (await mergeInProgress(root)) return false;
  // Same scope as the renderer, which refuses an artifact-free tree: drift/**/*.md except any INDEX.md.
  const names = await fs.readdir(drift, { recursive: true });
  if (!names.some((name) => name.endsWith(".md") && basename(name) !== "INDEX.md")) return false;
  const index = await safePath(root, join(drift, "INDEX.md"));
  const lock = await safePath(root, join(drift, ".publish.lock"));
  return withLock(lock, async () => {
    const content = await run(interpreter ?? await python(), ["-I", builder, drift, "--stdout"], root);
    if (!/^\| \d+ \|/m.test(content)) return false;
    if (await exists(index) && await fs.readFile(index, "utf8") === content) return false;
    await checkArtifactPolicy(root, index, tracked);
    const mode = await exists(index) ? (await fs.stat(index)).mode & 0o777 : 0o644;
    await atomicWrite(index, content, mode);
    return true;
  });
}

const sequenceOf = (name: string) => /^(\d{3})-.*\.md$/.exec(basename(name))?.[1];

/** Sequence numbers a feature already uses on any remote-tracking ref, as of the last fetch. No network. */
async function remoteSequenceNumbers(repo: string, feature: string): Promise<number[]> {
  const refs = (await git(repo, ["for-each-ref", "--format=%(refname)", "refs/remotes"], true)).split("\n").filter(Boolean);
  const numbers: number[] = [];
  for (const ref of refs) {
    const names = (await git(repo, ["ls-tree", "--name-only", ref, "--", `drift/${feature}/`], true)).split("\n");
    for (const name of names) { const sequence = sequenceOf(name); if (sequence) numbers.push(Number(sequence)); }
  }
  return numbers;
}

/** `repo` is the worktree doing the work (its branch and commit are recorded); `root` is where drift/ lives. */
async function prepare(repo: string, root: string, record: RecordData, input: ArtifactInput, digest: string, tracked: boolean): Promise<Pending> {
  const folder = await safePath(root, join(root, "drift", input.feature));
  await fs.mkdir(folder, { recursive: true });
  const numbers = (await fs.readdir(folder)).map(sequenceOf).filter((sequence): sequence is string => Boolean(sequence)).map(Number);
  // Committed artifacts travel: a number another worktree already landed upstream is taken even if it has not been pulled yet.
  if (tracked) numbers.push(...await remoteSequenceNumbers(repo, input.feature));
  const number = Math.max(0, ...numbers) + 1;
  if (number > 999) throw new Error("Feature has exhausted its three-digit sequence; choose a new feature explicitly");
  const sequence = String(number).padStart(3, "0");
  const path = `drift/${input.feature}/${sequence}-${input.kind}-${input.slug}.md`;
  const date = now();
  const fields: Record<string, unknown> = {
    date, branch: (await git(repo, ["symbolic-ref", "--short", "HEAD"], true)).trim() || "HEAD",
    git_commit: (await git(repo, ["rev-parse", "--verify", "HEAD"], true)).trim() || null,
    feature: input.feature, sequence, type: input.kind, status: statuses[input.kind][0],
    session_started: record.started, session_id: record.sessionId, interval_id: record.intervalId,
    start_branch: record.startBranch, start_commit: record.startCommit,
  };
  for (const name of ["status", "source_research", "previous_handoff", "related_artifacts", "next_session_profile"] as const) {
    if (input[name] !== undefined) fields[name] = input[name];
  }
  const frontmatter = Object.entries(fields).map(([key, value]) => `${key}: ${JSON.stringify(value)}`).join("\n");
  const content = `---\n${frontmatter}\n---\n\n${input.body}`;
  // The fragment is named after the artifact, so two threads' fragments can never share a name.
  const fragment = input.changelog ? {
    path: `changelog.d/${input.feature}-${sequence}-${input.slug}.md`,
    content: `---\ndate: ${JSON.stringify(date)}\nsection: ${JSON.stringify(input.changelog.section)}\nartifact: ${JSON.stringify(path)}\n---\n${input.changelog.text}\n`,
  } : undefined;
  return { digest, path, kind: input.kind, date, content, sha256: hash(content), ...(fragment ? { fragment } : {}) };
}

function validatePending(record: RecordData, pending: Pending): void {
  // Reject corrupt/edited state rather than following arbitrary paths in it.
  if (pending.fragment !== undefined && (!fragmentPathPattern.test(pending.fragment.path) || typeof pending.fragment.content !== "string")) {
    throw new Error("Invalid pending changelog fragment; record left untouched for recovery");
  }
  if (!artifactPathPattern.test(pending.path) ||
      !/^[a-f0-9]{64}$/.test(pending.digest) || typeof pending.content !== "string" || hash(pending.content) !== pending.sha256 ||
      !pending.content.includes(`session_id: ${JSON.stringify(record.sessionId)}\n`) ||
      !pending.content.includes(`interval_id: ${JSON.stringify(record.intervalId)}\n`)) {
    throw new Error("Invalid pending publication; record left untouched for recovery");
  }
}

/** Code, not the model, supplies identity/frontmatter and completes the interval. */
export async function publish(store: Records, raw: ArtifactInput, interpreter?: string): Promise<Receipt> {
  // Everything is resolved under the record lock, so an explicit adoption cannot interleave with publication.
  // `active` is the measured worktree (metadata, fragments, config); `root` is where drift/ lives. store.repo is only the record anchor.
  return store.update(async (record) => {
    const active = await store.effectiveRepo(record);
    const config = await driftConfig(active);
    const tracked = config.trackArtifacts;
    const { root } = await artifactStore(active, tracked);
    const input = await validate(root, raw, (await changelogState(active)).enabled);
    const drift = await safePath(root, join(root, "drift"));
    await fs.mkdir(drift, { recursive: true });
    const index = await safePath(root, join(drift, "INDEX.md"));
    const lock = await safePath(root, join(drift, ".publish.lock"));
    return withLock(lock, async () => {
      const digest = hash(JSON.stringify({ interval: record.intervalId, input }));
      const receipt = record.receipts.find((item) => item.digest === digest);
      if (record.pending && record.pending.digest !== digest) throw new Error(`Incomplete publication ${record.pending.path}; retry the SAME input before publishing another artifact`);
      if (record.completed && !receipt) throw new Error("This work interval already has a handoff; start a new working prompt before publishing more");
      const pending = record.pending ?? (receipt ? undefined : await prepare(active, root, record, input, digest, tracked));
      const relativePath = pending?.path ?? receipt!.path;
      if (!artifactPathPattern.test(relativePath)) throw new Error("Invalid publication path in record");
      const path = await safePath(root, resolve(root, relativePath));
      if (!relativePath.startsWith(`drift/${input.feature}/`)) throw new Error("Mismatched publication receipt");
      await ensureArtifactPolicy(root, [path, index], tracked);
      // Fragments live in the worktree and travel with the code, never in the (possibly shared) artifact store.
      const fragmentPath = pending?.fragment ? await safePath(active, resolve(active, pending.fragment.path)) : undefined;
      if (fragmentPath && (await git(active, ["check-ignore", "--no-index", fragmentPath], 1)).trim()) {
        throw new Error(`Git ignores ${pending!.fragment!.path}; changelog fragments must be committed with the code. Resolve the ignore rule, then retry the same input.`);
      }
      if (pending) {
        validatePending(record, pending);
        record.pending = pending;
        await store.save(record); // Persist the recovery intent BEFORE artifact/index writes.
        if (await exists(path)) {
          if (await fs.readFile(path, "utf8") !== pending.content) throw new Error(`Publication conflicts with existing file; nothing overwritten: ${relativePath}`);
        } else {
          // A complete staging file is linked into place exclusively: never overwrite another writer.
          const staged = join(dirname(path), `.drift-${digest}.tmp`);
          try {
            await atomicWrite(staged, pending.content, 0o644);
            await fs.link(staged, path);
          } finally { await fs.rm(staged, { force: true }); }
        }
      } else if (!(await exists(path)) || hash(await fs.readFile(path)) !== receipt!.sha256) {
        throw new Error(`Published artifact was removed or changed: ${relativePath}; receipt retained`);
      }
      if (pending?.fragment && fragmentPath) {
        await fs.mkdir(dirname(fragmentPath), { recursive: true });
        if (await exists(fragmentPath)) {
          if (await fs.readFile(fragmentPath, "utf8") !== pending.fragment.content) throw new Error(`Changelog fragment conflicts with an existing file; nothing overwritten: ${pending.fragment.path}`);
        } else {
          const staged = join(dirname(fragmentPath), `.drift-${digest}.tmp`);
          try {
            await atomicWrite(staged, pending.fragment.content, 0o644);
            await fs.link(staged, fragmentPath);
          } finally { await fs.rm(staged, { force: true }); }
        }
      }
      // One shared renderer; no second TS index implementation. stdout permits atomic replacement.
      const content = await run(interpreter ?? await python(), ["-I", builder, drift, "--stdout"], root);
      if (!content.includes(`](${relativePath.slice("drift/".length)})`)) throw new Error("Index renderer did not include the artifact");
      await safePath(root, index);
      const mode = await exists(index) ? (await fs.stat(index)).mode & 0o777 : 0o644;
      await atomicWrite(index, content, mode);
      if (await fs.readFile(index, "utf8") !== content) throw new Error("Index verification failed");
      const result: Receipt = receipt ?? { digest, path: pending!.path, kind: pending!.kind, date: pending!.date, sha256: pending!.sha256, ...(pending!.fragment ? { fragment: pending!.fragment.path } : {}) };
      if (!receipt) {
        await store.capture(record, "publish", active);
        record.receipts.push(result);
      }
      delete record.pending;
      if (input.kind === "handoff") record.completed = result;
      await store.save(record); // Failure here is retryable from the persisted pending intent.
      return result;
    });
  });
}
